name: update-dependency-graph
on:
  workflow_dispatch:

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.3
        with:
          gradle-build-module: |-
            :
            :tag-lib
          sub-module-mode: INDIVIDUAL
